import { ArrowUpRight, ArrowUpRightFromSquare, CalendarDays, Check, ChevronRight, Circle, Clock3, FileText, Filter, Lightbulb, MoreHorizontal, Plus, Sparkles } from 'lucide-react'
import type { WorkspaceSection } from '../../types'

const pageCopy: Record<Exclude<WorkspaceSection, 'Strategy' | 'Strategy Documents'>, { eyebrow: string; title: string; description: string }> = {
  Overview: { eyebrow: 'PROJECT HOME', title: 'Обзор проекта', description: 'Сводка активности, приоритетов и ключевых сигналов по проекту.' },
  Research: { eyebrow: 'KNOWLEDGE BASE', title: 'Исследования', description: 'Источники, рыночные сигналы и выводы, связанные с вашей стратегией.' },
  Documents: { eyebrow: 'PROJECT LIBRARY', title: 'Документы', description: 'Материалы проекта и рабочие документы команды.' },
  Planning: { eyebrow: 'ROADMAP', title: 'Планирование', description: 'Этапы, контрольные точки и зависимости на ближайший квартал.' },
  Tasks: { eyebrow: 'EXECUTION', title: 'Задачи', description: 'Следующие действия, которые приближают проект к цели.' },
  Insights: { eyebrow: 'SIGNALS & METRICS', title: 'Инсайты', description: 'Метрики и наблюдения для принятия стратегических решений.' },
  Settings: { eyebrow: 'WORKSPACE CONFIGURATION', title: 'Настройки проекта', description: 'Управление деталями и контекстом этого workspace.' },
}

const tasks = [
  { title: 'Провести интервью с потенциальными учениками', meta: 'Исследование · На этой неделе', state: 'progress' },
  { title: 'Сформулировать гипотезы целевых сегментов', meta: 'Стратегия · На этой неделе', state: 'open' },
  { title: 'Подготовить содержание пилотного курса', meta: 'Продукт · Следующая неделя', state: 'open' },
]

type Props = { section: Exclude<WorkspaceSection, 'Strategy' | 'Strategy Documents'>; fileName?: string; fileContent?: string }

export function WorkspacePage({ section, fileName, fileContent }: Props) {
  const current = pageCopy[section]
  const title = fileName ?? current.title
  return <div className="secondary-page">
    <div className="page-crumb"><span>PROJECT</span><ChevronRight size={12} /><span>{current.eyebrow}</span></div>
    <div className="secondary-heading"><div><span className="eyebrow">{current.eyebrow} <i /> UPDATED JUST NOW</span><h1>{title}</h1><p>{fileName ? 'Документ проекта · Markdown' : current.description}</p></div><button className="outline-button"><Plus size={14} /> Создать</button></div>
    {fileName ? <DocumentPreview fileName={fileName} content={fileContent} /> : section === 'Overview' ? <Overview /> : section === 'Tasks' ? <TaskBoard /> : section === 'Planning' ? <Planning /> : section === 'Research' ? <Research /> : section === 'Documents' ? <Documents /> : section === 'Insights' ? <Insights /> : <Settings />}
  </div>
}

function Overview() {
  return <>
    <div className="overview-stats">
      <Stat title="Стратегия" value="1 из 5" note="Текущее состояние определено" trend="+1 этап" />
      <Stat title="Открытые задачи" value="04" note="2 приоритета на этой неделе" trend="2 в работе" />
      <Stat title="Исследования" value="08" note="Источники в библиотеке" trend="+3 за неделю" />
      <Stat title="Здоровье проекта" value="Хорошее" note="Нет блокирующих рисков" trend="Стабильно" />
    </div>
    <div className="overview-grid"><section className="workspace-panel overview-focus"><div className="panel-heading"><div><span className="eyebrow">NEXT UP</span><h2>Фокус команды</h2></div><button className="subtle-link">Все задачи <ArrowUpRightFromSquare size={13} /></button></div>{tasks.slice(0, 2).map((task) => <TaskRow task={task} key={task.title} />)}<button className="panel-add"><Plus size={14} /> Добавить задачу</button></section><section className="workspace-panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">PROJECT SIGNALS</span><h2>Последние обновления</h2></div><MoreHorizontal size={17} /></div><ActivityRow icon={<Sparkles size={14} />} title="Стратегия обновлена" meta="Текущее состояние · 12 минут назад" /><ActivityRow icon={<FileText size={14} />} title="Добавлено исследование рынка" meta="market-analysis.md · 2 часа назад" /><ActivityRow icon={<Check size={14} />} title="Завершена задача" meta="Определить контекст проекта · вчера" /></section></div>
    <div className="workspace-panel priorities-panel"><div className="panel-heading"><div><span className="eyebrow">STRATEGY SNAPSHOT</span><h2>Ключевой ориентир</h2></div><span className="status-pill"><i /> В работе</span></div><div className="snapshot"><span className="snapshot-icon"><Lightbulb size={17} /></span><div><strong>Подтвердить спрос до масштабирования продукта</strong><p>Сначала провести интервью и проверить интерес к пилотному курсу. Это снизит риск инвестиций в неподтверждённый формат.</p></div><button className="icon-button"><ArrowUpRight size={16} /></button></div></div>
  </>
}

function TaskBoard() { return <div className="board-columns">{[['TO DO', '3'], ['IN PROGRESS', '2'], ['DONE', '6']].map(([title, count], column) => <section className="board-column" key={title}><div className="board-column-head"><span><i className={`column-marker column-${column}`} />{title}</span><small>{count}</small><button className="icon-button"><Plus size={14} /></button></div>{(column === 0 ? tasks.slice(1) : column === 1 ? tasks.slice(0, 1) : [{ title: 'Определить контекст проекта', meta: 'Стратегия · Вчера', state: 'done' }]).map((task) => <article className="task-card" key={task.title}><div><span className="task-priority">{column === 1 ? 'HIGH PRIORITY' : 'PROJECT TASK'}</span><button className="icon-button"><MoreHorizontal size={15} /></button></div><strong>{task.title}</strong><small><CalendarDays size={12} />{task.meta.split(' · ')[1]}</small><footer><span className="avatar-stack"><i>AK</i><i>ML</i></span><span className={`task-tag ${column === 1 ? 'tag-blue' : ''}`}>{task.meta.split(' · ')[0]}</span></footer></article>)}</section>)}</div> }

function Planning() { return <div className="planning-panel workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Q3 · 2026</span><h2>План запуска</h2></div><button className="outline-button"><CalendarDays size={14} /> Квартал</button></div>{[['01', 'Исследование аудитории', 'Провести интервью и определить сегмент', '2 недели', 'complete'], ['02', 'Проверка концепции', 'Страница ожидания и тест предложения', '3 недели', 'active'], ['03', 'Пилотный запуск', 'Первая когорта и сбор обратной связи', '4 недели', 'upcoming']].map(([number, name, desc, duration, status], index) => <div className={`roadmap-item roadmap-${status}`} key={number}><div className="roadmap-marker">{status === 'complete' ? <Check size={13} /> : number}</div><div className="roadmap-copy"><span>PHASE 0{index + 1} <i /> {status.toUpperCase()}</span><strong>{name}</strong><p>{desc}</p></div><span className="roadmap-duration"><Clock3 size={12} />{duration}</span></div>)}</div> }

function Research() { return <div className="research-list workspace-panel"><div className="panel-heading"><div><span className="eyebrow">8 SOURCES · 3 TOPICS</span><h2>Библиотека исследований</h2></div><button className="icon-button"><Filter size={15} /></button></div>{[['market-analysis.md', 'Рынок онлайн-образования', 'Рынок', 'Обзор динамики спроса и ключевых сегментов аудитории.', '12 Sep 2026'], ['competitors.md', 'Анализ конкурентной среды', 'Конкуренты', 'Сравнение форматов обучения, позиционирования и цен.', '10 Sep 2026'], ['technologies.md', 'Технологический стек обучения', 'Технологии', 'Инструменты и платформы для пилотного запуска курса.', '08 Sep 2026']].map(([file, name, type, desc, date]) => <article className="research-row" key={file}><span className="research-file-icon"><FileText size={16} /></span><div><strong>{name}</strong><p>{desc}</p><small>{file}</small></div><span className="research-tag">{type}</span><span className="research-date">{date}</span><button className="icon-button"><ArrowUpRight size={15} /></button></article>)}</div> }

function Documents() { return <div className="documents-grid">{[['current-state.md', 'Стратегия', 'Обзор ресурсов, ограничений и возможностей проекта.', '12 минут назад'], ['roadmap.md', 'Планирование', 'Этапы и контрольные точки пилотного запуска.', 'Сегодня'], ['market-analysis.md', 'Исследования', 'Рыночные сигналы и сегменты пользователей.', 'Вчера'], ['summary.md', 'Документы', 'Краткая сводка контекста проекта.', '10 Sep 2026']].map(([file, folder, desc, edited]) => <button className="document-card" key={file}><span className="document-card-icon"><FileText size={17} /></span><span className="document-card-folder">{folder.toUpperCase()}</span><strong>{file}</strong><p>{desc}</p><small><Clock3 size={12} /> {edited}</small></button>)}</div> }

function Insights() { return <><div className="overview-stats"><Stat title="Интервью" value="12" note="из 15 запланированных" trend="80%" /><Stat title="Интерес к пилоту" value="68%" note="предварительные ответы" trend="+12%" /><Stat title="Гипотезы" value="03" note="одна требует проверки" trend="В работе" /><Stat title="Риски" value="02" note="без критических" trend="Низкий уровень" /></div><div className="workspace-panel insight-chart"><div className="panel-heading"><div><span className="eyebrow">VALIDATION SIGNALS</span><h2>Динамика подтверждения гипотез</h2></div><button className="subtle-link">Последние 30 дней <ChevronRight size={13} /></button></div><div className="chart-legend"><span><i /> Интервью</span><span><i /> Список ожидания</span></div><div className="chart-area"><div className="chart-y-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div><div className="chart-grid"><div className="chart-line line-one"><i /><i /><i /><i /><i /><i /><i /></div><div className="chart-line line-two"><i /><i /><i /><i /><i /><i /><i /></div><div className="chart-x-labels"><span>01 Sep</span><span>05 Sep</span><span>10 Sep</span><span>15 Sep</span><span>20 Sep</span><span>25 Sep</span></div></div></div></div></> }

function Settings() { return <div className="settings-layout"><nav className="settings-nav"><button className="selected">Project details</button><button>Team & access</button><button>AI context</button><button>Notifications</button></nav><section className="workspace-panel settings-form"><div className="panel-heading"><div><span className="eyebrow">GENERAL</span><h2>Детали проекта</h2></div><button className="outline-button">Сохранить</button></div><label>Название проекта<input defaultValue="Tech Education Platform" /></label><label>Описание<textarea defaultValue="Разработка образовательной платформы для изучения технологий" /></label><label>Цель проекта<input defaultValue="Проверить спрос на практическое tech-обучение" /></label><label>Часовой пояс<select defaultValue="Europe/Moscow"><option value="Europe/Moscow">Europe / Moscow (UTC+3)</option><option value="UTC">UTC</option></select></label></section></div> }

function DocumentPreview({ fileName, content }: { fileName: string; content?: string }) { return <article className="document-preview workspace-panel"><div className="document-preview-meta"><span><FileText size={14} /> {fileName}</span><span>Markdown <i /> Только в workspace</span></div><div className="document-preview-content"><span className="eyebrow">PROJECT DOCUMENT · LAST EDITED TODAY</span><h2>{fileName.replace('.md', '').replace(/-/g, ' ')}</h2>{content ? <pre className="generated-document-content">{content}</pre> : <><p>Рабочий документ проекта Tech Education Platform. Здесь собраны связанные наблюдения, решения и следующие шаги.</p><h3>Контекст</h3><p>Материалы этого документа пока хранятся локально в интерфейсе. Используйте его как пространство для структурирования проектных заметок.</p><h3>Следующие шаги</h3><ul><li>Уточнить гипотезы и связанные доказательства</li><li>Добавить владельца и дату следующего пересмотра</li><li>Связать документ с этапом стратегии</li></ul></>}<div className="document-ai-note"><Sparkles size={15} /><span><strong>Контекст для AI-агента</strong><small>Этот документ доступен агенту в рамках текущего проекта.</small></span></div></div></article> }

function Stat({ title, value, note, trend }: { title: string; value: string; note: string; trend: string }) { return <article className="stat-card"><span>{title}</span><strong>{value}</strong><small>{note}</small><i>{trend}</i></article> }
function TaskRow({ task }: { task: typeof tasks[number] }) { return <div className="overview-task"><span className={`task-checkbox ${task.state === 'progress' ? 'task-checkbox-active' : ''}`}>{task.state === 'progress' && <Circle size={6} fill="currentColor" />}</span><span><strong>{task.title}</strong><small>{task.meta}</small></span><span className="task-owner">AK</span></div> }
function ActivityRow({ icon, title, meta }: { icon: React.ReactNode; title: string; meta: string }) { return <div className="activity-row"><span>{icon}</span><div><strong>{title}</strong><small>{meta}</small></div><ChevronRight size={14} /></div> }